### ISSUE TITLE
"Choose File" it doesn't look like a button

### ISSUE THREAD

**Issue by adorade** [adorade/boodark#13]
In "dark-mode", `<input class="form-control" type="file">` it does not stand out. File upload button "Choose File" is not clearly a button. See https://github.com/phpmyadmin/themes/issues/92

**Comment by adorade** [comment]
Option 1, extend '.btn-dark'
![button-choose-file-server-opt-1](https://user-images.githubusercontent.com/6474149/199025452-777dfd36-ea24-4fd6-9817-4685077400ba.png)

Option 2, extend '.btn-outline-info'
![button-choose-file-server-opt-2](https://user-images.githubusercontent.com/6474149/199025674-4b504992-bef9-40c4-9928-221d22a30ba1.png)

```scss
input {
  &[type=file]::-webkit-file-upload-button {
    @extend .btn-dark;
    // @extend .btn-outline-info;
    border-width: 1px;
    border-style: solid;
  }
}
```

I prefer option 1. Tested in Chrome.
