### ISSUE TITLE
PMA 5.1 - selected tab shows "(current)" next to tab name

### ISSUE THREAD

**Issue by Oleg-dM** [adorade/boodark#5]
PMA 5.1 - selected tab shows "(current)" next to tab name

![image](https://user-images.githubusercontent.com/8371571/198248965-c83ec7d3-ebde-48a8-9323-7ecac866f8f3.png)

**Comment by Oleg-dM** [comment]
Also, is there a way to decrease the font size of the theme?
Thanks for the great work

**Comment by adorade** [comment]
@Oleg-dM I'm glad you like the BooDark theme and thank you for reporting this issue.

Themes for pma v5.1 use Bootstrap v4, while themes for pma v5.2 use Bootstrap v5.1.3. Because of this, some incompatibilities appear that generate problems. BooDark is based on the Bootstrap theme (pma 5.2.0). For this reason, I will not make changes in the theme to fully support pma v5.1.

My advice is to upgrade to pma v5.2.0. If, for various reasons, you want to use pma v5.1, you can customize `theme.css` by adding the missing classes or modifying the existing ones.

In your case, you can add at the end of `theme.css`:

```css
/* decrease the font size of the theme  */
body {
  font-size: 14px !important;
}
/* add support for screen readers  */
.sr-only {
  position: absolute;
  width: 1px;
  height: 1px;
  padding: 0;
  margin: -1px;
  overflow: hidden;
  clip: rect(0, 0, 0, 0);
  white-space: nowrap;
  border: 0;
}
```
